from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class ProcessInfo:
	"""Runtime details about a single process."""

	pid: int
	name: str
	cpu_percent: float
	memory_mb: float
	memory_percent: float
	status: str
	create_time: float
	num_threads: int
	io_read_bytes: Optional[int] = None
	io_write_bytes: Optional[int] = None
	username: Optional[str] = None


@dataclass
class SystemSnapshot:
	"""Point-in-time system metrics and top process information."""

	timestamp: float
	cpu_percent: float
	cpu_per_core: List[float]
	memory_total_mb: float
	memory_used_mb: float
	memory_percent: float
	swap_percent: float
	disk_read_bytes_per_sec: float
	disk_write_bytes_per_sec: float
	net_bytes_sent_per_sec: float
	net_bytes_recv_per_sec: float
	process_count: int
	top_processes: List[ProcessInfo]
	boot_time: float


@dataclass
class Issue:
	"""Structured diagnosis output for one detected problem."""

	id: str
	category: str
	severity: str
	title: str
	cause: str
	explanation: str
	confidence: float
	affected_processes: List[str]
	suggestion: str
	evidence: Dict[str, object]

	def clamp_confidence(self) -> None:
		"""Clamp confidence to the inclusive [0.0, 1.0] range."""
		self.confidence = max(0.0, min(1.0, self.confidence))


@dataclass
class DiagnosticReport:
	"""Complete diagnostic result generated by the intelligence engine."""

	timestamp: float
	snapshot_summary: Dict[str, object]
	issues: List[Issue] = field(default_factory=list)
	system_health_score: float
	changes_detected: List[Dict[str, object]] = field(default_factory=list)
	anomalies_detected: List[Dict[str, object]] = field(default_factory=list)

